CREATE TABLE accounts
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name     VARCHAR(255)                            NOT NULL,
    last_name      VARCHAR(255)                            NOT NULL,
    gender         VARCHAR(255)                            NOT NULL,
    age            INTEGER                                 NOT NULL,
    email          VARCHAR(255)                            NOT NULL,
    industry       VARCHAR(255)                            NOT NULL,
    photo_url      VARCHAR(255),
    banner_img_url VARCHAR(255),
    country        VARCHAR(255),
    city           VARCHAR(255),
    phone_number   VARCHAR(255),
    headline       VARCHAR(255),
    about          VARCHAR(255),
    education      VARCHAR(255),
    user_id        BIGINT,
    CONSTRAINT pk_accounts PRIMARY KEY (id)
);

ALTER TABLE accounts
    ADD CONSTRAINT uc_accounts_email UNIQUE (email);

ALTER TABLE accounts
    ADD CONSTRAINT uc_accounts_user UNIQUE (user_id);

ALTER TABLE accounts
    ADD CONSTRAINT FK_ACCOUNTS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);